### ISSUE TITLE
Webpack2 support

### ISSUE THREAD

**Issue by mmrath** [Va1/string-replace-loader#10]
Looks like even with https://github.com/Va1/string-replace-loader/commit/2668cda1e73b614e27457608ad0a67fa60ccefc7 people have warnings of missing webpack. That is the reason there is a forked repo at https://github.com/gdi2290/string-replace-loader . Any chance we can use the any webpack version?

**Comment by zigzag95** [comment]
Please use * for webpack version

**Comment by ValeryVS** [comment]
This is because 2.x.x is not include 2.x.x-beta

**Comment by Va1** [comment]
@mmrath @zigzag95 
hey, guys, I see the problem and I am pretty sure that @ValeryVS is right about why that notification is shown. I don't think that putting `*` there is a nice decision, as it brings confusion (I am not sure if webpack plugins had the same syntax and workflow all the way, so making such assumption without checking is not the way dependencies should be managed). But regarding adding that `-beta` - OK, I will apply a fix (I am not a fan of this kind of fix, but I'm at your service).

**Comment by mmrath** [comment]
@Va1 Looks like 1.0.4 still does not address this issue

npm WARN string-replace-loader@1.0.4 requires a peer of webpack@1.x.x || 2.x.x || 2.x.x-beta but none was installed.

**Comment by ValeryVS** [comment]
I test some cases.
It looks like x-ranges is not work for peerDependencies.
Also, beta versions must be picked with all minor versions.
Just `>=2.0.0-beta` is not include `2.1.0-beta`.

With `1 || 2 || ^2.0.0-beta || ^2.1.0-beta` there will be no warning.

**Comment by ValeryVS** [comment]
Other working examples

webpack-dev-middleware
```
  "peerDependencies": {
    "webpack": "1 || ^2.1.0-beta"
  },
```

webpack-dev-server
```
  "peerDependencies": {
    "webpack": "^2.1.0-beta"
  },
```

**Comment by ValeryVS** [comment]
X-ranges not works with prerelease versions.
On "dependencies", "devDependencies" and "peerDependencies"

**Comment by ValeryVS** [comment]
Made a PR with this fix
#12

**Comment by ValeryVS** [comment]
`1.x.x || 2.x.x` is equal to `1 || 2` because npm semver except three numbers as a version.

**Comment by Va1** [comment]
@ValeryVS 
thanks a lot, `1.0.5` is published and includes your commit
