### ISSUE TITLE
Does this loader have access to bundle names?

### ISSUE THREAD

**Issue by deiga** [Va1/string-replace-loader#13]
I'm trying to replace my hashed bundle names in my templates and was wondering if I can accomplish it with this loader? :)

**Comment by aserrabl** [comment]
+1

**Comment by Va1** [comment]
hi guys. it does not, as webpack loaders work only with the source code of the chunks, while bundle names is smth related to webpack mechanisms and chunks metadata, which lies outside of the scope of the project anyways.
