### ISSUE TITLE
Webpack peer dependency in v1.0.5

### ISSUE THREAD

**Issue by radio-miskovice** [Va1/string-replace-loader#17]
I forked and cloned angular2-webpack-starter and after I started playing with it, I get the following warning all the time:

    npm WARN string-replace-loader@1.0.5 requires a peer of webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta but none was installed.

I have webpack 2.2.0-rc.4 in dev dependencies.  Should I downgrade or should the loader v1.0.5 be less picky?

**Comment by Va1** [comment]
@radio-miskovice 
My guess is that one should not use beta and RC versions of software, when more recent release versions are available. Peer deps will be cleared to contain only release versions in a while.
