### ISSUE TITLE
DeprecationWarning: loaderUtils.parseQuery()

### ISSUE THREAD

**Issue by Al1mirage** [Va1/string-replace-loader#20]
Hi there, today we start getting an deprecation warning which is caused by using parseQuery() method. Here is a full text of warning:
node : (node:2124) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
At line:1 char:1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : NotSpecified: ((node:2124) Dep...utils/issues/56:String) [], RemoteException
FullyQualifiedErrorId : NativeCommandError
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

**Comment by lebowski89** [comment]
+1

**Comment by donaldpipowitch** [comment]
@Va1 Seems to be an easy fix. I made a PR https://github.com/Va1/string-replace-loader/pull/22

**Comment by RoystonS** [comment]
Btw, there already appears to be another PR for it: PR #21 ?

**Comment by donaldpipowitch** [comment]
Nice, haven't seen that. I guess it wasn't linked to this issue correctly. Maybe it is slightly better - there are some minor differences in the PRs.

**Comment by Va1** [comment]
PR is merged, changes will be included in the next minor version I will publish now. Thank you, sorry for the delay.
