### ISSUE TITLE
I am unable to use this. I want chnage assets path in generated js file in build.

### ISSUE THREAD

**Issue by bankimatglobant** [Va1/string-replace-loader#27]
I am unable to use this. I want change assets path in generated js file in build. Please provide me detail steps to implement this. 

Currently, I have added below code in webpack.dev.js file.

module: {
      loaders: [
        {
          test: /.*/,
          loader: 'string-replace',
          query: {
            search: 'locales',
            replace: 'bankim',
          },
          exclude: /node_modules/
        }
      ],

And use npm install --save-dev string-replace-loader

Let me know if I miss something.

**Comment by limitlessloop** [comment]
This worked for me. I wasn't sure why it wasn't doing anything, even though I didn't think there was more than one occurrence, but adding this flag meant there must have been a match somewhere that I couldn't see.

**Comment by Va1** [comment]
@limitlessloop thanks for posting, glad it helped you out. i assume i can close this thread now
