### ISSUE TITLE
warning "string-replace-loader@1.2.0" has incorrect peer dependency "webpack@1 || 2".

### ISSUE THREAD

**Issue by damianobarbati** [Va1/string-replace-loader#30]
Time to update peerDependencies for webpack 3? :)

**Comment by spencerbeggs** [comment]
This loader is still working fine for me. I don't think there were any breaking changes.

**Comment by damianobarbati** [comment]
@spencerbeggs yep, nothing broken just a warning.

**Comment by spencerbeggs** [comment]
Looks like they already have a PR: https://github.com/Va1/string-replace-loader/pull/29

**Comment by Va1** [comment]
PR merged, thank you, guys
