### ISSUE TITLE
Double quotation marks string replace issue

### ISSUE THREAD

**Issue by bitfella** [Va1/string-replace-loader#36]
Hello,
I am trying to remove the following string `@charset "UTF-8";` from Webpack's css output.
I am using the following configuration:

```
          loader: 'string-replace-loader',
          query: {
            multiple: [
              {
                search: '@charset "UTF-8";', 
                replace: '_____AAAAA_____',
                flags: 'ig'
              }              
            ]
          }
```

but it does not seems to work, unfortunately.
I noticed the following webpack log on my terminal:
```
"search":"@charset /"UTF-8/";","replace":"_____AAAAA_____","flags":"ig"
```
I guess something's wrong with the way the regexp is created, since it appends slashes, building up a wrong string that does not exists in my css.

Any idea?
Thanks

**Comment by tomJasen** [comment]
Hello: 
This is because the character does not escape.
you can test npm package : 'webpack-replace-loader'

**Comment by Va1** [comment]
characters are not escaped intentionally, as if they were escaped, plugin would have been useless in cases when you really want to specify a regex replacement. please, read the docs carefully. thank you
