### ISSUE TITLE
string-replace vs string-replace-loader

### ISSUE THREAD

**Issue by ianengelbrecht** [Va1/string-replace-loader#37]
For your documentation, webpack gives this message:

BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'string-replace-loader' instead of 'string-replace',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed

**Comment by hanzhangyu** [comment]
This is just a demo for webpack 1, I think. So if you use other version, fixed it youself please.

**Comment by Va1** [comment]
readme updated. thanks everyone
