### ISSUE TITLE
Feature request: callbacks

### ISSUE THREAD

**Issue by balping** [Va1/string-replace-loader#40]
Would be great if I could specify a callback function as a replacement like:

```js
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'string-replace-loader',
        options: {
          search: 'my name',
          replace: function(result){
                  return result.toUpperCase();
          },
          flags: 'gi'
        }
      }
    ]
  }
}
```

**Comment by Hanterdro** [comment]
+1

It would be very easy to implement:

After the native `String.replace` implementation is used you can easy use function in `replaced` instead of a string. Only the `optionsSchema` object has to be adjusted to allow also a function.

**Comment by Va1** [comment]
implemented. thanks
