### ISSUE TITLE
Getting an unexpected token error when trying to process .json files

### ISSUE THREAD

**Issue by lopugit** [Va1/string-replace-loader#44]
I've got some language translation files, I was hoping to parse them but when I include .json in the test regex I get an unexpected token error, you may need an appropriate loader to handle this file type

`WARNING in ./src/client/locales/or-IN.json
Module parse failed: Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
| {
|   "hero": "Ensuring compensation for the creators of value",
|   "search": "Search",
|   "search_placeholder": "Search...",
 @ ./src/client/locales lazy ^\.\/.*$
 @ ./src/client/translations/index.js
 @ ./src/client/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3456 ./src/client/index.js`

**Comment by dvdtth** [comment]
sounds like you're missing a loader for *.json file types
in your webpack config file, add this

{
    test: /\.json$/,
    loader: 'json-loader'
}

**Comment by Va1** [comment]
the above comment indicates the issue. closing this. cheers
