### ISSUE TITLE
Error: Cannot define 'query' and multiple loaders in loaders list

### ISSUE THREAD

**Issue by Axure** [Va1/string-replace-loader#5]
If you have multiple loaders, you won't be able to use this loader. You will receive the error message:

> Error: Cannot define 'query' and multiple loaders in loaders list

**Comment by Va1** [comment]
Hey!

Indeed, you can not define query this way when there's multiple loaders. But there's a way to do that (not very elegant, though), have a look at [this](https://github.com/Va1/string-replace-loader/blob/master/test/index.test.js#L184) lines in the test suite.

**Comment by Va1** [comment]
I assume, this one is resolved, thanks ;)

**Comment by airtonix** [comment]
Ca't you just code it so it looks for a configuration object in the webpack config object?

```es6
...

	{
		test: /\.scss$/,
		loaders: [
			'style',
			'css',
			'postcss',
			'string-replace?config=stringReplaceAssetPaths',
			'sass',
		]
	},
...
stringReplaceAssetPaths: {
  mulitple: [
    { search: '{{ static.root }}', replace: config.assets.public },
    { search: '{{ cdn.root }}', replace: config.assets.cdn },
  ]
},
...
```

**Comment by airtonix** [comment]
https://github.com/webpack/loader-utils#getloaderconfig

**Comment by shprink** [comment]
Here is an example with Webpack2:

```
{
          test: /service-worker\.js$/,
          use: [
            'file-loader?name=[name].[ext]',
            `string-replace-loader?search=VERSION&replace="${pkg.version}"`
          ]
 }
```
