### ISSUE TITLE
Unexpected token on 'static' declaration

### ISSUE THREAD

**Issue by bwallrich** [Va1/string-replace-loader#57]
Hello,

got an error with webpack 4.20.2 and string-replace-loader 2.1.1 on my static declaration.
if  i comment this line, everything work file.
```javascript
ERROR in ./Users.js 14:21
Module parse failed: Unexpected token (14:21)
File was processed with these loaders:
 * ./node_modules/string-replace-loader/index.js
You may need an additional loader to handle the result of these loaders.
| export default class Users  {
| 
>     static myVar = 'users';
|    
| 
 @ ...
```

**Comment by Va1** [comment]
hi,

i believe, this is due to the fact that you're not using a loader configured to support this `static` syntax, which's unrelated to webpack or this loader itself. if it is still an issue, refer to ECMAScript proposals and babel loader configuration.

cheers
