### ISSUE TITLE
Webpack v5 support

### ISSUE THREAD

**Issue by martinoppitz** [Va1/string-replace-loader#59]

**Comment by Va1** [comment]
thank you very much for submitting both PRs!

however, when releasing i've noticed that the package actually did not work with Webpack 5, as well as with the new versions of dependencies. so i had to investigate and apply fixes.

next time, when contributing to OSS, please, make sure you things work and tests pass, before submitting a contribution.

cheers

**Comment by Va1** [comment]
[3.0.0](https://github.com/Va1/string-replace-loader/releases/tag/v3.0.0) released
