### ISSUE TITLE
Plain replacement only replace first instance of match

### ISSUE THREAD

**Issue by jiaweihli** [Va1/string-replace-loader#6]
I expected plain replacement to match all instances.

Workaround: pass `flags: 'g'` for regex global match.

**Comment by Va1** [comment]
The plugin behavior is intended to be the same as [Strimg.prototype.replace](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace). This should be mentioned in documentation, sorry.

**Comment by Va1** [comment]
I did update the readme.

**Comment by jiaweihli** [comment]
Thanks!
