### ISSUE TITLE
Application not able to search and replace in css file

### ISSUE THREAD

**Issue by webfriend13** [Va1/string-replace-loader#7]
I am trying to search and replace in a CSS file without any success.  Please confirm if I can search and replace text in a case file or this is a bug.

**Comment by Aaltuj** [comment]
i have this issue also with scss. Is this loader not capable of doing css/scss replacement??

**Comment by uweg** [comment]
I have the same issue with LESS. However, I found a way to fix it.

Does not work:
```js
{
  test: /\.less$/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: {
        localIdentName: '[local]--[hash:base64:5]',
        sourceMap: true
      }
    },
    {
      loader: 'less-loader',
      options: {
        sourceMap: true
      }
    },
    {
      loader: 'string-replace-loader',
      options: {
        search: 'placeholder',
        replace: 'replacement',
        flags: 'g'
      }
    }
  ]
}
```

Works:
```js
{
  test: /\.less$/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: {
        localIdentName: '[local]--[hash:base64:5]',
        sourceMap: true
      }
    },
    {
      loader: 'string-replace-loader',
      options: {
        search: 'placeholder',
        replace: 'replacement',
        flags: 'g'
      }
    },
    {
      loader: 'less-loader',
      options: {
        sourceMap: true
      }
    }
  ]
}
```

For whatever reason, the order of the loaders seems to be important.

**Comment by palakt4f** [comment]
Hi @uweg 

I have the same situation and I try your tricks but I'm getting this:-

`
    ERROR in ./node_modules/css-loader?{"modules":true,"camelCase":true,"importLoaders":1}!./node_modules/string-replace-loader?{"search":{},"replace":"../public","flags":"g"}!./node_modules/postcss-loader/lib?{"plugins":[null,null]}!./node_modules/less-loader/dist/cjs.js!./client/assets/less/style.less
    Module not found: Error: Can't resolve '../public/img/common-bg.png' in 'D:\temp\test\tours4fun\palak.react\client\assets\less'
     @ ./node_modules/css-loader?{"modules":true,"camelCase":true,"importLoaders":1}!./node_modules/string-replace-loader?{"search":{},"replace":"../public","flags":"g"}!./node_modules/postcss-loader/lib?{"plugins":[null,null]}!./node_modules/less-loader/dist/cjs.js!./client/assets/less/style.less 6:1001-1039`

**Comment by palakt4f** [comment]
But, it works when I put it on the top.

```
{
                test: /\.less$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: [
                        {
                           loader: "string-replace-loader",
                           options: {
                               search: "placeholder",
                               replace: "replacement",
                               flags: "g",
                           },
                       }, {
                            loader: "css-loader",
                            options: {
                                modules: true,
                                camelCase: true,
                                importLoaders: 1,
                            },
                        }, {
                            loader: "postcss-loader",
                            options: {
                                plugins: [
                                    autoprefixer({
                                        browsers: [
                                            "last 2 versions",
                                            "Firefox ESR",
                                            "> 1%",
                                            "ie >= 8",
                                            "iOS >= 8",
                                            "Android >= 4",
                                        ],
                                    }),
                                    pxtorem({
                                        rootValue: 100,
                                        propWhiteList: [],
                                    }),
                                ],
                            },
                        },
                        "less-loader",
                    ],
                }),
            },
```

**Comment by Palaklive** [comment]
Hi @uweg

I have the same situation and I try your tricks but I'm getting this:-

ERROR in ./node_modules/css-loader?{"modules":true,"camelCase":true,"importLoaders":1}!./node_modules/string-replace-loader?{"search":{},"replace":"../public","flags":"g"}!./node_modules/postcss-loader/lib?{"plugins":[null,null]}!./node_modules/less-loader/dist/cjs.js!./client/assets/less/style.less Module not found: Error: Can't resolve '../public/img/common-bg.png' in 'D:\temp\test\tours4fun\palak.react\client\assets\less' @ ./node_modules/css-loader?{"modules":true,"camelCase":true,"importLoaders":1}!./node_modules/string-replace-loader?{"search":{},"replace":"../public","flags":"g"}!./node_modules/postcss-loader/lib?{"plugins":[null,null]}!./node_modules/less-loader/dist/cjs.js!./client/assets/less/style.less 6:1001-1039

**Comment by Palaklive** [comment]
But, it works when I put it on the top.

{
                test: /\.less$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: [
                        {
                           loader: "string-replace-loader",
                           options: {
                               search: "placeholder",
                               replace: "replacement",
                               flags: "g",
                           },
                       }, {
                            loader: "css-loader",
                            options: {
                                modules: true,
                                camelCase: true,
                                importLoaders: 1,
                            },
                        }, {
                            loader: "postcss-loader",
                            options: {
                                plugins: [
                                    autoprefixer({
                                        browsers: [
                                            "last 2 versions",
                                            "Firefox ESR",
                                            "> 1%",
                                            "ie >= 8",
                                            "iOS >= 8",
                                            "Android >= 4",
                                        ],
                                    }),
                                    pxtorem({
                                        rootValue: 100,
                                        propWhiteList: [],
                                    }),
                                ],
                            },
                        },
                        "less-loader",
                    ],
                }),
            },

**Comment by Va1** [comment]
sorry for delayed reply.

first of all, you can only specify options.search as a string, as this is how [webpack docs](https://webpack.js.org/configuration/module/#useentry) want you to do because wepback translates options to JSON and back before they get to the loader code.

regarding main issue: loaders ordering *does* matter and the fact that you can not replace after LESS or SASS loader did its job means that they somehow changed the contents in a way replacement does not work anymore. i am not sure though, will have a closer look into how CSS raw contents accessible to loaders look like when i have time. you should replace before preprocessing anyways, if you can.

**Comment by gregorskii** [comment]
Would it make sense for this to be a plugin then? If it were a plugin it could attach to a specific phase and enforce that it happens directly on the source files before it is compiled.

**Comment by Va1** [comment]
sorry for even more of a delayed reply lol.

there is a plugin which allows for replacements – [webpack.DefinePlugin](https://webpack.js.org/plugins/define-plugin/). it's also official. you can use it instead of this loader (i assume) or together with this loader, depending on what are you trying to achieve.

with my above note on the order of loaders and the absence of further essence of the issue, i'm closing it. let me know if i should reopen.

big thanks to all participants. cheers guys

**Comment by prma85** [comment]
@Va1 I am having the same issue

I have the `string-replace-loader` to load before sass. It does replace the `@import ..` but it is not replacing the content itself for variables. How can I use the webpack.DefinePlugin together to do the replace? Doesn't have any mention to it on the webpack documentation.

```js
const replaceList = [
  { search: /bootstrap-4/gi, replace: "bootstrap" },
  { search: /bootstrap-sass-official/gi, replace: "bootstrap-sass" },
  { search: /..\/..\/..\/..\/libs\/bootstrap/gi, replace: "bootstrap" },
  { search: /@import "bootstrap/gi, replace: '@import "~bootstrap' },
  { search: /@import "font-awesome/gi, replace: '@import "~font-awesome' },
  { search: /@import "libs\//gi, replace: '@import "~' },
  { search: "libs/font-awesome/fonts", replace: '/fonts' },
];
```

```js
loader: [
          MiniCssExtractPlugin.loader,
          {
            loader: "css-loader",
            options: {
              importLoaders: 3,
              sourceMap: true,
            },
          },
          {
            loader: "resolve-url-loader",
            options: {
              sourceMap: true,
            },
          },
          {
            loader: "sass-loader",
            options: {
              implementation: require("node-sass"),
              sassOptions: {
                sourceComments: true,
                outputStyle: "nested",
              },
              sourceMap: true,
            },
          },
          {
            loader: "string-replace-loader",
            options: {
              multiple: replaceList,
            },
          },
        ],
```

**Comment by cnt-null** [comment]
@Va1 DefinePlugin affects everything, even js files. So there is a risk of unwanted replacement.

I managed to solve the replacement issue in css. Perhaps it will be useful to someone.

For example, I have an `index.js` file containing `import 'styles.scss'`.
And `styles.scss` contains `@import '~semantic-ui-css/semantic.css'`.
I try to use the `string-replace-loader` to overwrite `semantic.css`.

When styles are processed by the loaders chain and reach the `MiniCssExtractPlugin.loader`, the imported styles look like this:

`import ___CSS_LOADER_AT_RULE_IMPORT_0___ from "-!../../node_modules/css-loader/dist/cjs.js!../../node_modules/semantic-ui-css/semantic.css";`

That is, the styles are not yet extracted from `semantic.css`.
Hence, the `string-replace-loader` cannot replace these styles.
But the problem can be solved like this:
Remove `@import '~semantic-ui-css/semantic.css'` from `styles.scss`.
Add `import 'semantic-ui-css/semantic.css'` to `index.js`.
